sudo: required
dist: trusty

# travis-ci does not have first-class support for octave
language: generic

addons:
  apt:
    sources:
    - sourceline: 'ppa:octave/stable'
    # not on trusty: http://ppa.launchpad.net/dac922/octave-unstable/ubuntu/pool/main/o/octave/
    # - sourceline: 'ppa:dac922/octave-unstable'
    packages:
    - octave
    - liboctave-dev

install:
  # sdpt3 and sedumi do not work with Octave 3.8.x :-( for Octave 4.0.0.+, try:

  # install sdpt3
  - git clone https://github.com/sqlp/sdpt3.git /tmp/sdpt3
  - cd /tmp/sdpt3 && octave --eval "install_sdpt3; savepath"

  # install sedumi
  - git clone https://github.com/sqlp/sedumi.git /tmp/sedumi
  - cd /tmp/sedumi && octave --eval "install_sedumi; savepath"

  # install doctest
  - git clone https://github.com/catch22/octave-doctest.git /tmp/doctest
  - cd /tmp/doctest && make test
  - octave --eval "addpath('/tmp/doctest/inst', '/tmp/doctest/src'); savepath;"

script: cd ~/build/catch22/quantbox && make octave_test
